name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update with your AWS region

      # Terraform Init and Validate
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate
      
      # Terraform Plan (Pull Request)
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -out=tfplan

      # Terraform Apply (Push to Main)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
